### PR TITLE
Calendar rendering with styles and simple tests

### PR DESCRIPTION
**Pull request by winniefong1021**
Go to my ReadMe and follow the usage directions to see the calendar component.
Let me know if there are any styling you think I need to implement still.

### CODE REVIEW

**Comment by slhodak** [comment]
Happy to check it out after dinner if no one gets to it first!

**Comment by exzerone** [comment]
I can check!

**Comment by exzerone** [comment]
everything looks good, nice job!

**Review by exzerone — APPROVED** [review]
everything looks good! nice job!

**Pull request merged**
